name: 🛠️ Bug Report
description: Report an issue with Lucid Evolution
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |

        Thank you for helping us improve Lucid Evolution! Please fill out the details below to ensure we can address the issue efficiently.
        
         **Notes:**
        - ✅ Detailed reports help us resolve issues faster.
        - ❌ Vague or incomplete reports may be closed or delayed.

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue also mention it in the description.
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a minimal reproduction of the issue. If a report is vague, it will be marked as "needs-info".
      placeholder: |
        ```
        // Your minimal reproduction code here
        const lucid = ...    
        ```
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe the expected outcome, what should have happened?
      placeholder: Describe what you expected to happen
  - type: textarea
    id: system-info
    attributes:
      label: Error Details
      description: |
        Please provide:
        - Lucid Evolution version (check your package.json)
        - Terminal logs/error messages
      render: shell
      placeholder: Paste your error logs here
    validations:
      required: true
  - type: dropdown
    id: network
    attributes:
      label: Cardano Network
      description: Which Cardano network are you using?
      options:
        - Mainnet
        - Preprod
        - Preview
        - Custom
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the issue here.
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Read the [documentation](https://no-witness-labs.github.io/lucid-evolution/)
          required: true
        - label: Check that there isn't already an [issue](https://github.com/no-witness-labs/lucid-evolution/issues) that reports the same bug to avoid creating a duplicate
          required: true
        - label: The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) example of the bug
          required: true
